steps:
  #
  # Cocoa tests
  #

  # Fixtures must be built with 10.15+
  - label: Build cocoa IPA
    key: cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac-cocoa-11
    artifact_paths:
      - test/bugsnag-cocoa/features/fixtures/ios/output/iOSTestApp.ipa
      - test/bugsnag-cocoa/features/fixtures/macos/output/macOSTestApp.zip
    commands:
      - cd test/bugsnag-cocoa
      - ./features/scripts/export_ios_app.sh
      - ./features/scripts/export_mac_app.sh

  - label: 'macOS 10.14 E2E tests (subset)'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.3.0:
        download: ["test/bugsnag-cocoa/features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["test/bugsnag-cocoa/macOSTestApp.log", "test/bugsnag-cocoa/appium_server.log"]
    commands:
      - cd test/bugsnag-cocoa
      - bundle install
      - bundle exec maze-runner
        --farm=local
        --os=macos
        --os-version=10.14
        --app=macOSTestApp
        --tags='not @skip_macos'
        --fail-fast
        features/barebone_tests.feature

  - label: 'examples/objective-c-osx'
    commands:
      - cd test/bugsnag-cocoa/examples/objective-c-osx
      - echo "--- Pod install"
      - pod install
      - echo "+++ Build Release iOS"
      - xcodebuild -workspace objective-c-osx.xcworkspace -scheme objective-c-osx -configuration Release -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
      - echo "+++ Build Debug iOS Simulator"
      - xcodebuild -workspace objective-c-osx.xcworkspace -scheme objective-c-osx -configuration Debug -derivedDataPath DerivedData -quiet build GCC_TREAT_WARNINGS_AS_ERRORS=YES
