steps:
  #
  # Cocoa tests
  #
  - label: 'macOS 10.15 E2E tests (subset)'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.3.0:
        download: ["test/bugsnag-cocoa/features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["test/bugsnag-cocoa/macOSTestApp.log", "test/bugsnag-cocoa/appium_server.log"]
    commands:
      - cd test/bugsnag-cocoa
      - bundle install
      - bundle exec maze-runner
        --farm=local
        --os=macos
        --os-version=10.15
        --app=macOSTestApp
        --tags='not @skip_macos'
        --fail-fast
        features/barebone_tests.feature

  #
  # React Native tests
  #
  - label: 'Build React Native test fixture for iOS'
    key: "rn-0-60-ipa"
    timeout_in_minutes: 30
    env:
      REACT_NATIVE_VERSION: rn0.60
      NOTIFIER_VERSION: 7.10.1
    artifact_paths: test/bugsnag-js/build/rn0.60.ipa
    commands:
      - cd test/bugsnag-js
      - npm run test:build-react-native-ios

  #
  # Expo tests
  #
  - label:  'TEMP TEST'
    timeout_in_minutes: 3
    agents:
      queue: "opensource"
    command: "echo Test"

  - label:  ':docker: Build expo publisher'
    key: "expo-publisher"
    timeout_in_minutes: 30
    agents:
      queue: "opensource"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    plugins:
      - docker-compose#v3.7.0:
          config: test/bugsnag-js/docker-compose.yml
          build: expo-publisher
          image-repository: 855461928731.dkr.ecr.us-west-1.amazonaws.com/js
          cache-from:
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-platforms-infra
      - docker-compose#v3.7.0:
          config: test/bugsnag-js/docker-compose.yml
          push:
            - expo-publisher:855461928731.dkr.ecr.us-west-1.amazonaws.com/js:expo-publisher-platforms-infra

  - label: ':docker: Publish expo app'
    key: "publish-expo-app"
    depends_on: "expo-publisher"
    timeout_in_minutes: 20
    agents:
      queue: "opensource-highpower"
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    plugins:
      - docker-compose#v3.7.0:
          config: test/bugsnag-js/docker-compose.yml
          run: expo-publisher

  - label: ':docker: Build expo IPA'
    key: "build-expo-ipa"
    depends_on:
      - "publish-expo-app"
    timeout_in_minutes: 20
    env:
      EXPO_RELEASE_CHANNEL: ${BUILDKITE_BUILD_ID}
    artifact_paths: build/output.ipa
    commands:
      - cd test/bugsnag-js
      - test/expo/scripts/build-ios.sh

  #
  # SAM
  #
  - label: ':aws-lambda: AWS Lambda tests'
    timeout_in_minutes: 35
    commands:
      # force the NPM registry as the default on CI is artifactory, which can't
      # currently install from our lockfile
      - cd test/bugsnag-js
      - npm ci --registry https://registry.npmjs.org
      - cd test/aws-lambda
      - bundle install
      - bundle exec maze-runner
