steps:
  #
  # Cocoa tests
  #

  # Fixtures must be built with 10.15+
  - label: Build cocoa IPA
    key: cocoa_fixture
    timeout_in_minutes: 20
    agents:
      queue: opensource-mac-cocoa-11
    artifact_paths:
      - features/fixtures/ios/output/iOSTestApp.ipa
      - features/fixtures/macos/output/macOSTestApp.zip
    commands:
      - ./features/scripts/export_ios_app.sh
      - ./features/scripts/export_mac_app.sh

  - label: 'macOS 10.13 E2E tests (subset)'
    depends_on:
      - cocoa_fixture
    timeout_in_minutes: 30
    plugins:
      artifacts#v1.3.0:
        download: ["test/bugsnag-cocoa/features/fixtures/macos/output/macOSTestApp.zip"]
        upload: ["test/bugsnag-cocoa/macOSTestApp.log", "test/bugsnag-cocoa/appium_server.log"]
    commands:
      - cd test/bugsnag-cocoa
      - bundle install
      - bundle exec maze-runner
        --farm=local
        --os=macos
        --os-version=10.13
        --app=macOSTestApp
        --tags='not @skip_macos'
        --fail-fast
        features/barebone_tests.feature

  - label: macOS 10.13 unit tests
    timeout_in_minutes: 10
    commands:
      - ./scripts/run-unit-tests.sh PLATFORM=macOS
    artifact_paths:
      - logs/*
